package org.addycaddy.pojo;

public enum ContactPointType {
    BillingAddress,
    BillingEmail,
    BillingFax,
    BillingPhone,
    BusinessAddress,
    BusinessEmail,
    BusinessFax,
    BusinessPhone,
    HomeAddress,
    HomeEmail,
    HomeFax,
    HomePhone,
    LocationAddress,
    LocationEmail,
    LocationFax,
    LocationPhone,
    ShippingAddress,
    WorkAddress,
    WorkEmail,
    WorkFax,
    WorkPhone,
}
